var indexArrLang = {
  "en": {
    "Home": "Home",
    "About": "About",
    "Feature": "Feature",
    "Team": "Team",
    "Roadmap": "Roadmap",
    "Whitepaper": "Whitepaper",
    "Contact": "Contact",
    "Language": "Language",
    "badge": "Update",
    "integration-text": "Discover the best solutions for your business ",
    "fadeInUp1": "A.I. Computing Power Resource Network Designed for the Future",
    "w-textFadeInUp": "Next-Generation Blockchain A.I. Ecology.Maximize The Positive and Transformative Impact of A.I. Bring blockchain scenarios to a whole new level.",
    "btn_dream-btn": "Learn more",
    "wow_fadeInUp": "With Blockchain decentralized technology,we re-designed a network , connecting computing power of the world , build a better tomorrow for A.I.",
    "autoML": "A suite of machine learning products that enables developers with limited machine learning expertise to train high-quality models specific to your business needs, by leveraging transfer learning, and Neural Architecture Search technology.Custom model , migration learning , neural search network. ",
    "mlEngine": "HAI ML Engine host service. A auto Resource provisioning and monitoring engine.Support Multiple Frameworks scikit-learn, XGBoost, Keras, TensorFlow models.Real-time prediction hosting, no Docker container required.",
    "HPU": "A next-generation stunning High-speed AI chip. HPU, accelerates training model in machine learning. MUCH More efficient than former CPUs and GPUs.HAI AutoML is the best machine learning environment compatible with HAI HPU",
    "wow_fadeInUp1": "HAI is a operation environment designed for A.I. High performance , Low-cost hardware and software architecture.",
    "wow_fadeInUp2": "HAI chain provides sufficient computing resources, for custom model , migration learning , neural search network , to make HAI AutoML structure evolvable and optimizable.",
    "wow_fadeInUp3": "We created a new stack for AI computing resources network.",
    "btn_dream-btn_mt-30_wow_fadeInUp": "Read More",
    "wow_fadeInUp4": "Watch our demo video",
    "wow_fadeInUp5": "Find out why HAI Chain can be",
    "wow_fadeInUp6": "the game changer in Artificial Intelligence and Blockchain.",
    "wow_fadeInUp7": "A.I. become more powerful than every before when with blockchain.",
    "wow_fadeInUp8": "HAI Chain used the decentralized technology of blockchain to ensure that the large-scale AI computing network build is neutral. ",
    "wow_fadeInUp9": "We create an encrypted artificial intelligence computing network for enterprises, which is of great value to enterprises that require artificial intelligence services.",
    "fadeInUp2": "HAI Auto ML Core Features",
    "fadeInUp3": "The large-scale AI computing power network proposed by HAI Chain will have the following features",
    "Ready_to_use": "Ready to use",
    "Ready_to_use2": "Custom model , migration learning , neural search network. HAI AutoML is more evolvable and optimizable.",
    "Large_scale": "Large scale",
    "Large_scale2": "HAI’s unique hardware and software architecture for AI computing is ready for future large-scale AI computing needs.",
    "High_performance": "High performance",
    "High_performance2": "The next-generation stunning High-speed AI chip , accelerates training model in machine learning. More efficient than former CPUs and GPUs.",
    "Low_cost": "Low cost",
    "Low_cost2": "By training and running multiple experiments in our super-nodes, developers only need to focus on model development and deployment without worrying about infrastructure issues, HAI ML Engine do all resource provisioning and monitoring automatically.",
    "Portable": "Portable",
    "Portable2": "You can also import scikit-learn, XGBoost, Keras, and TensorFlow models that have been trained anywhere for fully-managed, real-time prediction hosting ,no Docker container required. ",
    "Easy": "Easy to use",
    "Easy2": "AutoML is a suite of machine learning products that enables developers with limited machine learning expertise to train high-quality models specific to your business needs by transfer learning and neural architecture search technology.",
    "Got": "Got you Wherever you need.",
    "Easily": "Easily retrieve the entire network of computing power resources.",
    "Deploy": "Deploy fully automatically. ",
    "Adapt": " Adapt to geodetic needs continuously",
    "Usable": "Usable & Sharable ",
    "Usable2": "Only sharing the data in the same structure or format that makes it usable. Change the status of data silos . Make data sharing a reality.",
    "Valuable": "Valuable &  Immutable",
    "Valuable2": "blockchains’ most significant advantage , immutability , we can eliminate redundant data , make all data more valuable than before..",
    "Exchangable": "Exchangable & Implementational",
    "Exchangable2": "Resource exchange center , make cooperation between different subjects in the chain.",
    "TechnicalTeam": "HAI Chain Technical team is a team of experts, backed by top-tier investors.",
    "CTO": "Chief Technical Officer",
    "CPO": "Chief Product Officer",
    "DOE": "Director of Engineering",
    "Roadmap": "Roadmap",
    "whitepaper": "For more detailed information of our project and distribution, please download complete whitepaper below.",
    "btnCMC": "Check Market Cap",
    "FQ": "Frequently Questions",
    "FQD": "Here are some common questions about HAI Chain and HAI token.",
    "FQ1": "Where can I get HAI Chain token?",
    "FQ2": "HAI Chain token is avalible on ",
    "FQA2": "HAI Chain token , HAI , will be use as a proof contribution in the computing resource network between supplies and demands. ",
    "FQ3": "What can I get with HAI Chain token?",
    "FQA3": "It's the very early stage of HAI Chain development, you can help us set up as many supernodes as possbile to strength the first testnet of the whole project.",
    "FQ4": "What is the public test start date?",
    "FQA4": "We are working on our pace to the track. We will announce at the first time on official website. Or you can subscribe to our mailing list and get the newest information.",
    "FQ5": "How may I take part in the project?",
    "FQA5": "HAI Chain is now still in development stage. If you have passion in joining us , please get to us via contact@hangkei.ai.",
    "LatestNews": "LatestNews",
    "news1": "HAI Project Successfully Launched",
    "news1d": "We focus on the development of computing power. from the most direct side, to meet the development of future AI.",
    "btnDetail": "Read Details",
    "news2": "Partnership with Europe and Africa",
    "news2d": "HAI token has been authorized as a Main Digital Assest in international trading , accepted in export and import settlement.",
    "news3": "Upcoming event , Blockchain Summit 2019",
    "news3d": "Hangkei honoured to be the host of Blockchain Summit 2019. Hangkei will announce more information of the event later.",
    "ContactUs": "CONTACT US",
    "ContactDetail": "Please leave us your words and email address, we will get back to you soon. Also subscribe to mailing list and get the firsthand updates.",
    "Name": "Name",
    "Email": "Email",
    "Subject": "Subject",
    "Message": "Message",
    "btnSend": "Send and Subscribe",
    "Hangkei": "Hangkei A.I. is an A.I. development research company founded in 2008. R&D and sales are aimed at achieving practical market applications, and fostering the AI industry-wide ecology.",
    "Exchanges": "Exchanges and Market Trackers",
    "ZBG": "ZBG Global Exchange",
    "Biz-Z": "Bit-Z Trading Platform",
    "NAVIGATE": "NAVIGATE",
    "Developers": "Developers",
    "Resources": "Resources",
    "Company": "Company",
    "Area": "APAC Regional Head Quarter",
    "Location1": "Sunshine Plaza , Lockhart Rd 353 ",
    "Location2": " Wanchai, Hong Kong ",
  },
  "zh": {
    "Home": "首页",
    "About": "关于",
    "Feature": "技术要点",
    "Team": "团队",
    "Roadmap": "发展规划",
    "Whitepaper": "白皮书",
    "Contact": "联系我们",
    "Language": "语言",
    "badge": "更新",
    "integration-text": "发现适合您业务的最佳解决方案",
    "fadeInUp1": "为未来而设的人工智能算力资源网络",
    "w-textFadeInUp": "次时代区块链人工智能生态使用神经网络变革性的冲击与激励最大化颠覆区块链使用场景",
    "btn_dream-btn": "了解更多",
    "wow_fadeInUp": "利用区块链的技术，重新构建网络，连接世界的计算能力，我们为AI计算资源网络构建了一个新的堆栈",
    "autoML": "一套机器学习产品，通过利用转移学习 和神经网络搜索，使只具有有限的机器 学习专业知识的开发人员，也能够根据 业务需求培训高质量模型。支持自定义 模型、迁移学习、神经搜索网络。",
    "mlEngine": "机器学习引擎与服务。自动资源配置和监视引擎。支持多个框架scikit-learn、XGBoost、Keras、TensorFlow模型。实时预测托管，不需要Docker容器。",
    "HPU": "新一代令人惊叹的高速AI芯片⸺HPU，加速机器学习中的培训模式，比以前的CPU和GPU高效达30倍。而HAI的Auto ML是与HAI HPU兼容的最佳 机器学习环境。",
    "wow_fadeInUp1": "HAI是为A.I.设计的操作环境。高性能，低成本的硬件和软件架构。",
    "wow_fadeInUp2": "HAI链提供足够的计算资源，用于自定义模型，迁移学习，神经搜索网络，使HAI AutoML结构可进化和可优化。",
    "wow_fadeInUp3": "我们为AI计算资源网络创建了一个新的堆栈。",
    "btn_dream-btn_mt-30_wow_fadeInUp": "了解更多",
    "wow_fadeInUp4": "观看视频",
    "wow_fadeInUp5": "了解为什么HAI Chain可以成为",
    "wow_fadeInUp6": "人工智能和区块链中的游戏规则改变者。",
    "wow_fadeInUp7": "A.I.使区块链变得比以前更强大。",
    "wow_fadeInUp8": "HAI Chain使用区块链的分散技术来确保大规模的AI计算网络构建是中立的。",
    "wow_fadeInUp9": "我们为企业创建了一个加密的人工智能计算网络，对需要人工智能服务的企业具有重要价值。",
    "fadeInUp2": "HAI算力网络核心功能",
    "fadeInUp3": "HAI Chain提出的大规模AI算力网络具备以下特点",
    "Ready_to_use": "简单使用",
    "Ready_to_use2": "Auto ML是一套机器学习产品使具有有限机器学习专业知识的开发人员，也能够通过转移学习和神经架构搜索技术，训练特定业务需求的高质量模型",
    "Large_scale": "支持大规模运算",
    "Large_scale2": "HAI独特的人工智能计算硬件和软件架构已为未来的大规模人工智能计算需求做好准备。",
    "High_performance": "高性能",
    "High_performance2": "新一代令人惊叹的软硬件架构加速了机器学习训练模式比过往任何方案都更高性能",
    "Low_cost": "低成本",
    "Low_cost2": "通过人工智能网络搜索最佳匹配算力资源，自动匹配，将大型和小型算力整合到资源网络并重新分配是HAI的设计目标",
    "Portable": "可迁移",
    "Portable2": "您还可以导入Scikit-learn，XGBoost，Keras和TensorFlow模型，这些模型已经过任何地方的培训，可以完全管理，实时预测托管，无需Docker容器",
    "Easy": "简单使用",
    "Easy2": "Auto ML是一套机器学习产品使具有有限机器学习专业知识的开发人员，也能够通过转移学习和神经架构搜索技术，训练特定业务需求的高质量模型",
    "Got": "找到你需要的地方。",
    "Easily": "轻松检索整个网络的计算能力资源。",
    "Deploy": "完全自动部署。",
    "Adapt": "不断适应大地测量需求。",
    "Usable": "高可用，可共享",
    "Usable2": "仅以相同的结构或格式共享数据以使其可用。更改 数据孤岛的状态。使数据共享成为现实。",
    "Valuable": "不可篡改性带来的价值最大化",
    "Valuable2": "基于不可篡改账本技术，可识别冗余数据;使所有 数据比以前更具有价值。",
    "Exchangable": "解决数据孤岛化",
    "Exchangable2": "资源交换中心，使链中的不同主体之间进行合作",
    "TechnicalTeam": "HAI Chain技术团队是由顶级投资者支持的专家团队。",
    "CTO": "首席技术官",
    "CPO": "首席产品经理",
    "DOE": "工程总监",
    "Roadmap": "发展规划",
    "whitepaper": "有关我们项目和分发的更多详细信息，请下载完整的白皮书。",
    "btnCMC": "检查市值",
    "FQ": "常见问题",
    "FQD": "以下是有关HAI Chain和HAI令牌的一些常见问题。",
    "FQ1": "我在哪里可以获得HAI token？",
    "FQ2": "这个标记的目标是什么？",
    "FQA2": "HAI token和HAI将用作供应和需求之间的计算资源网络中的证明贡献。",
    "FQ3": "使用HAI Chain令牌可以获得什么？",
    "FQA3": "这是HAI Chain开发的早期阶段，您可以帮助我们设置尽可能多的超级节点，以加强整个项目的第一个测试网络",
    "FQ4": "什么是公开测试开始日期？",
    "FQA4": "我们正在努力迈向赛道。我们将在官方网站上首次公布。或者您可以订阅我们的邮件列表并获取最新信息。",
    "FQ5": "我怎么能参与这个项目？",
    "FQA5": "HAI Chain目前仍处于开发阶段。如果您有兴趣加入我们，请通过contact@hangkei.ai联系我们。",
    "LatestNews": "最新消息",
    "news1": "HAI项目成功启动",
    "news1d": "我们专注于计算能力的发展。从最直接的一面，来满足未来AI的发展。",
    "btnDetail": "阅读细节",
    "news2": "与欧洲和非洲的伙伴关系",
    "news2d": "HAI令牌已被授权为国际贸易中的主要数字资产集合，在出口和进口结算中被接受。",
    "news3": "即将到来--2019区块链峰会",
    "news3d": "恒基很荣幸成为2019区块链峰会的东道主.恒基将在稍后公布更多有关该活动的信息。",
    "ContactUs": "联系我们",
    "ContactDetail": "请留下您的文字和电子邮件地址，我们会尽快给您回复。还订阅邮件列表并获得第一手的更新。",
    "Name": "名字",
    "Email": "邮箱",
    "Subject": "主题",
    "Message": "信息",
    "btnSend": "发送和订阅",
    "Hangkei": "Hangkei A.I.是发展研究A.I.的公司，成立于2008年。研发和销售旨在实现实际的市场应用，并促进人工智能行业的生态学。",
    "Exchanges": "交易所和市场追踪者",
    "ZBG": "ZBG全球交易所",
    "Biz-Z": "Bit-Z交易平台",
    "NAVIGATE": "导航",
    "Developers": "开发者",
    "Resources": "资源",
    "Company": "公司",
    "Area": "亚太区总部",
    "Location1": "香港特别行政区",
    "Location2": "香港湾仔骆克道353号",
  }
};

$(".translateLang ul li").click(function() {
  isHide = true;
  $(".translateLang").css("display","none");
  initLang(indexArrLang,$(this).attr("id"));
  if ($(this).attr("id")=="zh") {
    console.log("zh");
    $("#videobtn").attr("href","https://v.qq.com/x/page/v0865gj0o9c.html");
  }else {
    console.log("en");
    $("#videobtn").attr("href","https://www.youtube.com/watch?v=2pVSbjXP8XI");
  }
});
